### PR TITLE
Added "stats_correct/wrong_answers" translation

### PR DESCRIPTION
**Pull request by WhoRegisteredAllTheGoodUsernames**

### CODE REVIEW

**Comment by blastrock** [comment]
As always, thank you!

I am preparing a new release with a few changes in the vocabulary section. May I ask of you that you rebase this PR on master and translate the messages that I changed/added?

Here's a diff of what I did, I applied some of it to the Spanish translations with my limited knowledge.

```diff
diff --git a/README.rst b/README.rst
index 161c29a..a08d38b 100644
--- a/README.rst
+++ b/README.rst
@@ -42,6 +42,9 @@ Credits
 - The vocabulary quizzes are based on `JMdict <http://www.edrdg.org/jmdict/j_jmdict.html>`_.
 - The kanji similarity database comes from https://minerva-access.unimelb.edu.au/handle/11343/35336 and http://lars.yencken.org/datasets/phd/
 - The kanji composition and drawing database comes from `KanjiVG <https://kanjivg.tagaini.net/>`_.
+- The JLPT classification data comes from `Jonathan Waller <https://www.tanos.co.uk/jlpt/>`_.
+- The app icon font is `Nagayama Kai <https://www.freejapanesefont.com/nagayama-kai-calligraphy-font-download/>`_.
+- The app title font is `Fonters <https://www.dafont.com/fonters.font>`_.
 
 License
 =======
diff --git a/app/src/main/res/values/strings.xml b/app/src/main/res/values/strings.xml
index e43b215..acc5d43 100644
--- a/app/src/main/res/values/strings.xml
+++ b/app/src/main/res/values/strings.xml
@@ -12,9 +12,8 @@
     <string name="word_selection">Word selection</string>
     <string name="select_all">Select all</string>
     <string name="select_none">Select none</string>
-    <string name="autoselect_from_kanji">Automatically select words from selected kanji</string>
-    <string name="autoselect_from_kanji_short">Auto</string>
-    <string name="import_selection">Import kanji selection</string>
+    <string name="autoselect_from_kanji">Automatically select words</string>
+    <string name="import_selection">Import selection</string>
     <string name="database_error">Database error</string>
     <string name="custom_test">Custom test</string>
     <string name="select_test_types">Select the desired types of questions:</string>
@@ -93,7 +92,8 @@
     <string name="override_selection_title">Automatically select vocabulary</string>
     <string name="override_selection_msg">Do you want to select words based on your selected kanji?\nThis will override your current vocabulary selection.</string>
     <string name="could_not_import_file">Could not import file: %1$s</string>
-    <string name="import_kanji_help">This feature allows importing a kanji selection from a file. The file must contain all the kanji to be imported, on a single line, without space or any separator.</string>
+    <string name="import_kanji_help">This feature allows importing a kanji selection from a file. The file must contain one kanji per line. The kanji will be added to the current selection.</string>
+    <string name="import_words_help">This feature allows importing a word selection from a file. The file must contain one word per line. The words will be added to the current selection.</string>
     <string name="additional_kanji">Additional kanji</string>
     <string name="jlpt_level_n">JLPT level %1$s</string>
     <string name="rtk_index_range">Indexes %1$s+</string>
@@ -144,6 +144,7 @@
         <p>The vocabulary dictionary is based on <a href="http://www.edrdg.org/jmdict/j_jmdict.html">JMdict</a>.</p>
         <p>The kanji similarity data comes from <a href="http://lars.yencken.org/datasets/phd/">a study from Dr. Lars Yencken</a>.</p>
         <p>The kanji composition and drawing data comes from <a href="https://kanjivg.tagaini.net/">KanjiVG</a>.</p>
+        <p>The JLPT classification data comes from <a href="https://www.tanos.co.uk/jlpt/">Jonathan Waller</a>.</p>
         <p>The app icon font is <a href="https://www.freejapanesefont.com/nagayama-kai-calligraphy-font-download/">Nagayama Kai<a>.</p>
         <p>The app title font is <a href="https://www.dafont.com/fonters.font">Fonters<a>.</p>
 
@@ -153,14 +154,19 @@
     <string name="title_stats">Progress</string>
     <string name="stats_no_data">No data available yet. Your progress will appear here after you have taken tests.</string>
     <string name="stats_items_answered">Questions answered</string>
+    <string name="stats_correct_answers">Correct answers</string>
+    <string name="stats_wrong_answers">Wrong answers</string>
 
     <string name="changelog">Changelog</string>
     <string name="changelog_contents"><![CDATA[
```

**Comment by WhoRegisteredAllTheGoodUsernames** [comment]
Okay, done!. I hope I didn't mess with anything because it's the first time I've done this.

**Comment by blastrock** [comment]
Haha, don't worry, I'll fix everything when you're done ^^

Thanks a lot for fixing the readme!

There's just one thing: I want to keep in sync the "About" text in the app and the readme, it makes it easier for me if I need to copy paste something (especially in a language I don't know ^^). In the README, you wrote:

```
- La base de datos de similitud de kanji se basa en https://minerva-access.unimelb.edu.au/handle/11343/35336 y http://lars.yencken.org/datasets/phd/
```

And in the about dialog, there is:

```
        <p>Los datos de similitud de kanji son a cortesía de <a href="http://lars.yencken.org/datasets/phd/">un estudio del Dr. Lars Yencken</a>.</p>
```

I don't know which formulation is better, can you choose one and fix the other please?

**Comment by WhoRegisteredAllTheGoodUsernames** [comment]
These two are different because in the README the phrase is "The kanji similarity _database_ comes from..." and in the About dialog is "The kanji similarity _data_ comes from...", I didn't know if it was intentional or not at first, but I ended translating them accordingly anyway. Since they are not the same, ¿may I ask you to choose? 👀.

**Comment by blastrock** [comment]
You are right! Sorry for that ^^

I chose the one from the About string, I fixed the pull request and I'm merging it, thanks again!

**Pull request merged**
