### PR TITLE
Kana writing quizz

### PR DESCRIPTION
**Pull request by SavkovAlexander**
Add new test, that allows to learn kana to romaji by typing romaji equivalent.

### CODE REVIEW

**Comment by blastrock** [comment]
Thank you for the PR! I'll look at it soon enough :)

**Comment by blastrock** [comment]
I have finally looked at this and tested it. Here's a few things to fix if you can:

- Put the maybe and sure buttons on the same line as the text field, that's just wasted space on small screens.
- When you close the keyboard, the size of the coordlayout isn't restored. Same if you validate while the keyboard is closed, on the next screen, opening the keyboard will hide the main part of the screen. Maybe you should listen to some layout changed event.
- I saw you used TYPE_TEXT_FLAG_NO_SUGGESTIONS, there are still suggestions in the keyboard however. Maybe there's something more to do to hide them.
- Please rename the TestTextActivity class to TextTestActivity to match with the other activities.

Apart from that, it looks good, thanks again for your work :)

**Comment by SavkovAlexander** [comment]
Hi, blastrock.
I've fixed issues except problem with layout.

Layout autoresize normally until history view will be shown. After it layout stops autoresizing.

I've tried to fix it by removing unnecessary (as I think) scroll view from TextTestActivity (testLayout.wrapInScrollView). It helped and resizing works ok, but it breaks history (it layouts to the bottom of screen and is hidden by keyboard, when keyboard is open) and requestFocus.

Another idea was to always show keyboard (return true in EditorActionListener, set android:windowSoftInputMode="stateAlwaysVisible" and override onBackPressed), but I've don't found any way to prevent keyboard from closing using "back" button.

**Comment by blastrock** [comment]
Hmm ok, I will look into it and try to find something. Thank you for your efforts! :)

**Comment by blastrock** [comment]
If that's ok with you, I will add your name to the contributors. Should I write "Savkov Alexander"? Or do you have a preference for some nickname?

**Comment by blastrock** [comment]
I have fixed the keyboard issue. I am testing this new version and it's currently in beta on google play. If there is no issue, it will be released soon :)

**Comment by SavkovAlexander** [comment]
Great news :)
Thank you for creating this app!
You can add name to the contributor as "Savkov Alexander".
P.S. Should I close PR or you close it by yourself?

**Comment by blastrock** [comment]
I'll do it, thanks to you for the PR :)

**Comment by blastrock** [comment]
1.22 has been released, I squashed this PR into 201d905. Thanks again!

**Pull request closed without merging**
